In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

Attribute Information:

0 Date (DD/MM/YYYY)
1 Time (HH.MM.SS)
2 True hourly averaged concentration CO in mg/m^3 (reference analyzer)
3 PT08.S1 (tin oxide) hourly averaged sensor response (nominally CO targeted)
4 True hourly averaged overall Non Metanic HydroCarbons concentration in microg/m^3 (reference analyzer)
5 True hourly averaged Benzene concentration in microg/m^3 (reference analyzer)
6 PT08.S2 (titania) hourly averaged sensor response (nominally NMHC targeted)
7 True hourly averaged NOx concentration in ppb (reference analyzer)
8 PT08.S3 (tungsten oxide) hourly averaged sensor response (nominally NOx targeted)
9 True hourly averaged NO2 concentration in microg/m^3 (reference analyzer)
10 PT08.S4 (tungsten oxide) hourly averaged sensor response (nominally NO2 targeted)
11 PT08.S5 (indium oxide) hourly averaged sensor response (nominally O3 targeted)
12 Temperature in Â°C
13 Relative Humidity (%)
14 AH Absolute Humidity

In [2]:
pd.set_option('display.max_columns',None)
df = pd.read_csv('../data/AirQualityUCI/AirQualityUCI.csv',index_col=0)

In [3]:
df.iloc[:,2:] = df.iloc[:,2:].applymap(lambda x: float(x.replace(',','.')) if isinstance(x,str) else x)

In [4]:
df.sample(5)

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
7842,31/01/2005,12.00.00,3.1,1112.0,-200.0,12.8,1078.0,563.0,683.0,261.0,1028.0,1426.0,11.9,18.6,0.2581
3252,24/07/2004,06.00.00,0.7,968.0,-200.0,5.8,803.0,56.0,806.0,62.0,1586.0,1003.0,24.4,50.5,1.5243
2433,20/06/2004,03.00.00,1.4,-200.0,-200.0,-200.0,-200.0,-200.0,-200.0,-200.0,-200.0,-200.0,-200.0,-200.0,-200.0000
1444,09/05/2004,22.00.00,-200.0,1123.0,-200.0,8.9,937.0,-200.0,866.0,-200.0,1606.0,941.0,13.8,59.8,0.9398
9048,22/03/2005,18.00.00,3.3,1448.0,-200.0,20.9,1322.0,454.0,447.0,156.0,1655.0,1492.0,21.3,32.9,0.8209